# Comment to a new issue.
issuesOpened: >
  Thank you for raising this Adapter request.
  Please do not forget to vote for your request by "Thumbs up" on the fiirst post (not this one!). 

  **Also all interested users should do a "Thumbs up" instead of "+1" or "Me too" posts. Thank you!**

  How to do that: 
  <img width="595" alt="Bildschirmfoto 2022-05-29 um 18 30 47" src="https://user-images.githubusercontent.com/11976694/170880793-1d3f7ba4-b004-4944-a5f5-0f5c4873439e.png">
